# .github/auto_merge.yml
# SpectraMind V50 — Auto-Merge Configuration
# Governs when PRs can be automatically merged once conditions are satisfied.
# Ensure branch protections are enabled (required checks + approvals).

automerge:
  enabled: true

  # Target branches eligible for auto-merge
  branches:
    - main
    - develop

  # Preferred merge method (GitHub allows: merge, squash, rebase)
  method: squash

  # Labels that MUST be present before merge is attempted
  required_labels:
    - automerge
    - ci-passed

  # Labels that block auto-merge if present
  blocking_labels:
    - do-not-merge
    - needs-review
    - wip
    - blocked

  # Require at least 1 approval (in addition to branch protection rules)
  min_approvals: 1

  # Auto-delete source branch after merge
  delete_branch: true

  # Emit debug logs when evaluating PRs for auto-merge
  verbose: true

  # Optional: enforce successful security scans before merging
  required_checks:
    - lint
    - tests
    - security
    - sbom
    - trivy-scan
