# .pre-commit-config.yaml
# SpectraMind V50 — mission-grade pre-commit stack
# - Fast: ruff + black + isort
# - Safe: mypy + bandit + secrets scan
# - Repro: DVC guard + large-file protections
# - Docs: mdformat + spelling
# - Notebooks: strip outputs to keep diffs/Kaggle-friendly
# - JSON/YAML/TOML sanity checks
# - Optional: Conventional Commits (commit-msg)

ci:
  autofix_prs: true
  autoupdate_branch: true
  # Pre-commit.ci will try to fix formatting issues automatically in PRs

default_stages: [commit, push]
default_language_version:
  python: python3.11

repos:
  # ------------------------------
  # Core hygiene (generic)
  # ------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500]  # keep the repo lean; use DVC for data/artifacts
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-toml
      - id: detect-private-key

  # ------------------------------
  # Python formatting & linting
  # ------------------------------
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11
        files: ^(src/|tests/|scripts/|configs/|spectramind\.py)

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3.11
        args: [--profile=black, --filter-files]
        files: ^(src/|tests/|scripts/|configs/|spectramind\.py)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        # Fast flake8 replacement; see setup.cfg for config
        args: [--fix]
        files: ^(src/|tests/|scripts/|configs/|spectramind\.py)

  # ------------------------------
  # Static typing (fast path)
  # ------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          # Stubs/typing that are commonly used in the repo
          - pandas-stubs
          - numpy
          - types-PyYAML
          - types-requests
          - types-setuptools
        args:
          # mypy config lives in setup.cfg
          - --python-version=3.11
        files: ^(src/|spectramind\.py)

  # ------------------------------
  # Security
  # ------------------------------
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit (security scan)
        args: [-ll, -x, tests,docs,notebooks]
        exclude: ^(tests/|docs/|notebooks/)

  - repo: https://github.com/yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect-secrets (baseline)
        # Maintain .secrets.baseline in repo root. To (re)generate:
        #   detect-secrets scan > .secrets.baseline
        #   pre-commit run detect-secrets --all-files
        args: [--baseline, .secrets.baseline]

  # ------------------------------
  # DVC: keep data/models out of Git by mistake
  # ------------------------------
  - repo: https://github.com/iterative/dvc
    rev: 3.55.2
    hooks:
      - id: dvc-pre-commit
        name: dvc-pre-commit (guard Git vs DVC)
        pass_filenames: false
        stages: [commit]

  # ------------------------------
  # Notebooks: strip outputs to keep diffs small & Kaggle-safe
  # ------------------------------
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: \.ipynb$
        args: [--keep-count, --keep-output=false]

  # ------------------------------
  # Docs & text quality
  # ------------------------------
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        name: mdformat (Markdown formatter)
        additional_dependencies:
          - mdformat-gfm
          - mdformat-frontmatter
          - mdformat-footnote
          - mdformat-myst
        args: [--wrap, "88"]
        files: ^(README\.md|ARCHITECTURE\.md|docs/|.*\.md)$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [--ignore-words-list=nd,fo,te,ans,ot]  # tune ignore list as needed
        exclude: ^(poetry\.lock|.*\.lock|.*\.svg|assets/|docs/|.*\.ipynb)$

  # ------------------------------
  # JSON Schema sanity (schemas/)
  # ------------------------------
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.6
    hooks:
      - id: check-jsonschema
        name: JSON Schema metaschema check
        args: [--check-metaschema]
        files: ^schemas/.*\.json$

  # ------------------------------
  # Conventional commits (optional but recommended)
  # ------------------------------
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        name: commitizen (enforce Conventional Commits)
        stages: [commit-msg]
        additional_dependencies: ["cz-conventional-changelog"]
        # Requires .cz.toml or pyproject.toml with [tool.commitizen] config
