# ==============================================================================
# dvc.yaml — SpectraMind V50
# ------------------------------------------------------------------------------
# Reproducible pipeline:
#   calibrate → train → predict → (diagnose) → (submit)
#
# Tips
# - Use params.yaml to expose Hydra selectors (env/data/calib/model/training/loss/logger)
#   so `dvc exp show`/`dvc exp diff` can track config changes cleanly.
# - Processed data is 'persist' so downstream stages can reuse it across runs.
# - Training stage is dvclive-ready (uncomment if you log with dvclive).
# - Torch stack is handled outside DVC (e.g., bin/kaggle-boot.sh).
# ==============================================================================

stages:
  calibrate:
    wdir: .
    cmd: >
      spectramind calibrate
      --config-name ${params.hydra.config_name_calibrate}
      env=${params.hydra.env}
      data=${params.hydra.data}
      calib=${params.hydra.calib}
    deps:
      - configs/              # hydra configs (data/calib/env/...)
      - src/                  # calibration code
      - data/raw              # raw telescope inputs (DVC tracked)
    params:
      - hydra.config_name_calibrate
      - hydra.env
      - hydra.data
      - hydra.calib
    outs:
      - path: data/processed  # calibrated + preprocessed tensors
        persist: true

  train:
    wdir: .
    cmd: >
      spectramind train
      --config-name ${params.hydra.config_name_train}
      env=${params.hydra.env}
      data=${params.hydra.data}
      model=${params.hydra.model}
      training=${params.hydra.training}
      loss=${params.hydra.loss}
      logger=${params.hydra.logger}
    deps:
      - data/processed
      - configs/
      - src/
    params:
      - hydra.config_name_train
      - hydra.env
      - hydra.data
      - hydra.model
      - hydra.training
      - hydra.loss
      - hydra.logger
    outs:
      - path: artifacts/ckpt.pt
        cache: true
      - path: artifacts/metrics.json
        cache: true
      - path: logs/train/        # optional structured logs
        cache: false
    metrics:
      - artifacts/metrics.json:
          cache: false
          type: json
          xpath: .
    # Uncomment if you use dvclive (recommended for live learning curves)
    # live:
    #   path: dvclive
    #   summary: true
    #   html: true

  predict:
    wdir: .
    cmd: >
      spectramind predict
      --config-name ${params.hydra.config_name_predict}
      env=${params.hydra.env}
      data=${params.hydra.data}
    deps:
      - artifacts/ckpt.pt
      - data/processed
      - configs/
      - src/
    params:
      - hydra.config_name_predict
      - hydra.env
      - hydra.data
    outs:
      - path: outputs/preds.csv
        cache: true

  diagnose:
    wdir: .
    cmd: >
      spectramind diagnose
      --config-name ${params.hydra.config_name_diagnose}
      env=${params.hydra.env}
      data=${params.hydra.data}
    deps:
      - artifacts/ckpt.pt
      - outputs/preds.csv
      - configs/
      - src/
    params:
      - hydra.config_name_diagnose
      - hydra.env
      - hydra.data
    outs:
      - path: artifacts/diagnostics/report.html
        cache: true
      - path: artifacts/diagnostics/plots/
        cache: true
    plots:
      - artifacts/diagnostics/plots/    # png/svg/json — quick visual checks
    metrics:
      - artifacts/diagnostics/summary.json:
          cache: false
          type: json
          xpath: .

  submit:
    wdir: .
    cmd: >
      spectramind submit
      --config-name ${params.hydra.config_name_submit}
    deps:
      - outputs/preds.csv
      - configs/
      - src/
    params:
      - hydra.config_name_submit
    outs:
      - path: outputs/submission.csv
        cache: true
