# Hydra-compliant: groups live at root; Hydra settings stay in hydra: block.

# -----------------------------------------------------------------------------
# Composition from config groups
# -----------------------------------------------------------------------------
defaults:
  - env: local
  - data: default
  - calib: default
  - preprocess: default
  - model: v50
  - training: default
  - loss: composite
  - logger: jsonl
  - _self_

# -----------------------------------------------------------------------------
# Run-level knobs (reproducibility & convenience)
#   NOTE: oc.decode ensures types are parsed from env strings correctly.
# -----------------------------------------------------------------------------
seed: ${oc.decode:${oc.env:SM_SEED,42}}
deterministic: ${oc.decode:${oc.env:SM_DETERMINISTIC,true}}   # true|false
num_workers: ${oc.decode:${oc.env:SM_NUM_WORKERS,2}}          # int
precision: ${oc.decode:${oc.env:SM_TRAIN_PRECISION,32}}       # 16|bf16|32

# Canonical path surface (env-first, safe defaults)
paths:
  data_dir: ${oc.env:SM_DATA_DIR,./data}
  outputs_dir: ${oc.env:SM_OUTPUTS_DIR,./outputs}
  artifacts_dir: ${oc.env:SM_ARTIFACTS_DIR,./artifacts}
  cache_dir: ${oc.env:SM_CACHE_DIR,./.cache}

# Echo of active selections (for logging/diagnostics)
selections:
  env: local
  data: default
  calib: default
  preprocess: default
  model: v50
  training: default
  loss: composite
  logger: jsonl

# Canonical names for CLI subcommands (read by app, not Hydra)
config_name_calibrate: calibrate
config_name_preprocess: preprocess
config_name_train: train
config_name_predict: predict
config_name_diagnose: diagnose
config_name_submit: submit

# -----------------------------------------------------------------------------
# Hydra settings
# -----------------------------------------------------------------------------
hydra:
  # Reproducible, tidy run directories. Include job name and optional tag.
  run:
    dir: ${paths.outputs_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.name}${oc.env:SM_RUN_TAG,}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.name}${oc.env:SM_RUN_TAG,}
    subdir: ${hydra.job.num}

  job:
    chdir: true
    name: spectramind
    config:
      # Make override dirnames compact & deterministic (nice for CI artifacts)
      override_dirname:
        kv_sep: "="
        item_sep: ","
        exclude_keys: [seed, num_workers, precision]

  # Tighten unknown-key handling (only if supported by your Hydra version)
  strict: true

  # Allow disabling .hydra in CI: set HYDRA_OUTPUT_SUBDIR='.'
  output_subdir: ${oc.env:HYDRA_OUTPUT_SUBDIR,.hydra}

  # Quieter logging out of the box (can be overridden per-env)
  job_logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      simple:
        format: "[%(levelname)s] %(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        level: INFO
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers: [console]

  # (Optional) add packaged config search paths if you ship configs in-wheel
  # searchpath:
  #   - pkg://spectramind.configs