[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spectramind-v50"
version = "0.1.0"
description = "SpectraMind V50 — NeurIPS 2025 Ariel Data Challenge pipeline"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "typer[all]>=0.12",
  "hydra-core>=1.3",
  "omegaconf>=2.3",
  "pydantic>=2.7",
  "numpy>=1.26",
  "scipy>=1.11",
  "pandas>=2.2",
  "polars>=1.4",
  "pyyaml>=6.0",
  "torch>=2.2",
  "torchvision>=0.17",
  "lightning>=2.3",
  "torch-geometric>=2.5",
  "tqdm>=4.66",
  "rich>=13.7",
  "matplotlib>=3.8",
  "umap-learn>=0.5",
  "networkx>=3.2",
  "jsonschema>=4.22"
]

[project.scripts]
spectramind = "spectramind.cli:app"

[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B","C90"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
strict = true

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q"
