# configs/profiles/ci.yaml
# ======================================================================
# SpectraMind V50 — CI profile (debug data + fast trainer)
# Use:
#   python -m spectramind train +defaults='[/profiles/ci]'
# ======================================================================

defaults:
  # Optional tiny deterministic dataset slice (keep only if you have /data/debug)
  # - /data: debug

  # Short, deterministic trainer loop (includes sane logger/callbacks)
  - /training/fast_ci: fast_ci

  # Ensure we route through the training logger selector (offline-safe)
  - /training/logger: logger

# Reproducibility
seed: 123

# Force FP32 in CI (avoid AMP flakiness on shared runners)
precision:
  mode: "32-true"
  safety:
    detect_anomaly: false  # keep CI speedy

# Keep runs small, clean, deterministic (fast_ci already sets most of this)
trainer:
  log_every_n_steps: 10
  # (No enable_model_summary — deprecated in PL 2.x; use ModelSummary callback if needed)

# Deterministic DataLoader behavior for CI
data_loader:
  num_workers: 0
  persistent_workers: false
  pin_memory: false
  prefetch_factor: 2

# Paths (honor hydra.run.dir from base configs)
paths: {}
