# Deeper performance profiling
defaults:
  - /training/lightning: lightning
  - /training/precision: precision
  - /training/dataloader: dataloader

trainer:
  profiler: ${oc.env:SM_PROFILER,"advanced"}
  max_epochs: 3
  limit_train_batches: 0.2
  limit_val_batches: 0.2
  log_every_n_steps: 5

precision:
  mode: ${oc.env:SM_PRECISION,"bf16-mixed"}

data_loader:
  num_workers: ${oc.env:SM_WORKERS,4}
  persistent_workers: true
  prefetch_factor: 4
  pin_memory: true

experiment:
  tags: ["profile:profiling"]
