# configs/env/conda/CONDA_ENV.yml
# ======================================================================
# Conda Environment Spec — SpectraMind V50
# ======================================================================
# This file defines a reproducible Conda environment for local
# development and experimentation. Kaggle kernels should NOT rely on
# this file (use +env=kaggle instead). Dependencies are pinned where
# possible for reproducibility.
#
# Usage:
#   conda env create -f configs/env/conda/CONDA_ENV.yml
#   conda activate spectramind-v50
#
# Notes:
# - Torch + CUDA stack is specified via pip (to align with Kaggle wheels).
# - Dev/test extras are separated into requirements-dev.txt.
# - Environment is Python 3.10+ to match Kaggle runtime.
# ======================================================================

name: spectramind-v50
channels:
  - conda-forge
  - defaults

dependencies:
  # --- Core Python ---
  - python=3.10
  - pip>=23.2

  # --- Scientific stack ---
  - numpy>=1.24
  - pandas>=2.0
  - matplotlib>=3.8
  - scikit-learn>=1.3

  # --- Hydra / config management ---
  - hydra-core>=1.3
  - omegaconf>=2.3

  # --- CLI / UX ---
  - typer>=0.12
  - rich>=13.6

  # --- Dev / linting ---
  - black>=23.7
  - flake8>=6.1
  - mypy>=1.6
  - ruff>=0.1

  # --- Testing ---
  - pytest>=7.4
  - hypothesis>=6.87

  # --- Pip-only packages (Torch + Kaggle-safe wheels) ---
  - pip:
      - torch>=2.1
      - torchvision>=0.16
      - pytorch-lightning>=2.1
      - dvc[s3]>=3.20
      - wandb>=0.16
      - jsonschema>=4.19
      - seaborn>=0.13
