# SpectraMind V50 — Preprocess preset: nominal (balanced default)

preset: nominal
seed: 42

io:
  calibrated_root: ${data.exports.calibrated_root}
  features_root:   ${data.exports.features_root}
  overwrite: false
  format: "npz"              # 'npz' | 'parquet'

runtime:
  num_workers: 4
  pin_memory: true
  log_every_n: 100

# Stage selection
enable:
  load: true
  mask: true
  detrend: true
  normalize: true
  binning: true
  window: true
  pack: true
  tokenize: true
  augment: true             # train-only automatically enforced in code
  export: true

# Stage configs
load:        ${preprocess.method.load}
mask:        ${preprocess.method.mask}
detrend:     ${preprocess.method.detrend}
normalize:   ${preprocess.method.normalize}
binning:     ${preprocess.method.binning}
window:      ${preprocess.method.window}
pack:        ${preprocess.method.pack}
tokenize:    ${preprocess.method.tokenize}
augment:     ${preprocess.method.augment}
export:      ${preprocess.method.export}

# Global shapes
shapes:
  time_len: 512           # nominal T (after windowing)
  stride:   512           # non-overlapping by default
  bins: ${data.channels.airs.bins}

# Split policy (uses data.splits)
splits:
  source: ${data.splits.config}   # or inline settings from data profile
