# SpectraMind V50 — Preprocess preset: strict (research-grade)

preset: strict
seed: 9

io:
  calibrated_root: ${data.exports.calibrated_root}
  features_root:   ${data.exports.features_root}
  overwrite: false
  format: "parquet"

runtime:
  num_workers: 8
  pin_memory: true
  log_every_n: 50

enable:
  load: true
  mask: true
  detrend: true
  normalize: true
  binning: true
  window: true
  pack: true
  tokenize: true
  augment: true        # train-only; light physics-safe augs
  export: true

load:        ${preprocess.method.load}
mask:        ${preprocess.method.mask}
detrend:     ${preprocess.method.detrend}
normalize:   ${preprocess.method.normalize}
binning:     ${preprocess.method.binning}
window:      ${preprocess.method.window}
pack:        ${preprocess.method.pack}
tokenize:    ${preprocess.method.tokenize}
augment:     ${preprocess.method.augment}
export:      ${preprocess.method.export}

shapes:
  time_len: 640
  stride:   320             # 50% overlap for denser supervision
  bins: ${data.channels.airs.bins}

splits:
  source: ${data.splits.config}
