# configs/training/ablation.yaml
# ======================================================================
# SpectraMind V50 — Loss Ablation Profile (Upgraded)
# ======================================================================
# Zero all auxiliary physics-informed priors; keep GLL active.
# Usage:
#   spectramind train +defaults='[/training/ablation]'
# ======================================================================

loss:
  composite:
    weights:
      gll:            ${oc.env:SM_ABL_GLL, 1.0}   # main task on
      smoothness:     ${oc.env:SM_ABL_SMOOTH, 0.0}
      nonneg:         ${oc.env:SM_ABL_NONNEG, 0.0}
      band_coherence: ${oc.env:SM_ABL_BAND, 0.0}
      calibration:    ${oc.env:SM_ABL_CALIB, 0.0}

# Short, Kaggle/CI-friendly trainer tweaks
trainer:
  max_epochs:        ${oc.env:SM_ABL_EPOCHS, 25}
  val_check_interval:${oc.env:SM_ABL_VAL_INTERVAL, 0.5}   # validate 2×/epoch
  log_every_n_steps: ${oc.env:SM_ABL_LOG_EVERY, 20}

# Make runs easy to filter in JSONL/TB/W&B
experiment:
  tags: ${oc.env:SM_TAGS, ["ablation:priors=off", "gll=on"]}

# Reproducible, segregated outputs
hydra:
  run:
    dir: outputs/train-ablation/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/train-ablation/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
