# configs/training/ablation_calibration.yaml
# ======================================================================
# SpectraMind V50 — Ablate ONLY the calibration prior
# Usage:
#   spectramind train +defaults='[/training/ablation_calibration]'
# ======================================================================

loss:
  composite:
    weights:
      calibration: ${oc.env:SM_ABL_CALIB, 0.0}   # ablate only this prior

trainer:
  max_epochs: ${oc.env:SM_ABL_EPOCHS, 25}
  val_check_interval: ${oc.env:SM_ABL_VAL_INTERVAL, 0.5}
  log_every_n_steps: ${oc.env:SM_ABL_LOG_EVERY, 20}

# Make it obvious in dashboards/JSONL/TB
experiment:
  tags: ${oc.env:SM_TAGS, ["ablation:calibration=off"]}

hydra:
  run:
    dir: outputs/train-ablation/calibration/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/train-ablation/calibration/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
