# ======================================================================
# SpectraMind V50 — Ablate ONLY the smoothness prior
# Usage:
#   python -m spectramind train +defaults='[/training/ablation_smoothness]'
# ======================================================================

loss:
  composite:
    weights:
      # keep main task & other priors as-is (env-overridable)
      gll:          ${oc.env:SM_ABL_GLL, 1.0}
      nonneg:       ${oc.env:SM_ABL_NONNEG, null}
      band_coherence:${oc.env:SM_ABL_BAND, null}
      calibration:  ${oc.env:SM_ABL_CALIB, null}
      # ablate target prior
      smoothness:   ${oc.env:SM_ABL_SMOOTH, 0.0}

trainer:
  max_epochs: ${oc.env:SM_ABL_EPOCHS, 25}
  val_check_interval: ${oc.env:SM_ABL_VAL_INTERVAL, 0.5}
  log_every_n_steps: ${oc.env:SM_ABL_LOG_EVERY, 20}

hydra:
  run:
    dir: outputs/train-ablation/smoothness/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/train-ablation/smoothness/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
