# configs/training/ablation_nonneg.yaml
# ======================================================================
# SpectraMind V50 — Ablate ONLY the nonnegativity prior
# Usage:
#   spectramind train +defaults='[/training/ablation_nonneg]'
# ======================================================================

loss:
  composite:
    weights:
      nonneg: ${oc.env:SM_ABL_NONNEG, 0.0}   # ablate only this prior

trainer:
  max_epochs: ${oc.env:SM_ABL_EPOCHS, 25}
  val_check_interval: ${oc.env:SM_ABL_VAL_INTERVAL, 0.5}
  log_every_n_steps: ${oc.env:SM_ABL_LOG_EVERY, 20}

# Make it obvious in dashboards/JSONL
experiment:
  tags: ${oc.env:SM_TAGS, ["ablation:nonneg=off"]}

hydra:
  run:
    dir: outputs/train-ablation/nonneg/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/train-ablation/nonneg/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
