# ======================================================================
# SpectraMind V50 — ModelCheckpoint Config (Upgraded)
# ======================================================================
# Swapable Hydra config for PyTorch Lightning ModelCheckpoint callback.
# Provides env-driven overrides for monitoring, modes, retention, and
# filenames. Safe defaults tuned for Kaggle/CI reproducibility.
# ======================================================================

_target_: pytorch_lightning.callbacks.ModelCheckpoint

# ------------------------------ Monitoring ------------------------------
monitor: ${oc.env:SM_CKPT_MONITOR, "val/loss"}
mode: ${oc.env:SM_CKPT_MODE, "min"}    # "min" for loss/GLL; "max" for scores

# ------------------------------ Retention -------------------------------
save_top_k: ${oc.env:SM_CKPT_TOPK, 3}  # keep best N checkpoints
save_last: ${oc.env:SM_CKPT_LAST, true}
every_n_epochs: ${oc.env:SM_CKPT_EVERY_EPOCH, 1}
every_n_train_steps: ${oc.env:SM_CKPT_EVERY_STEPS, null}

# ------------------------------- Paths ----------------------------------
dirpath: ${oc.env:SM_CKPT_DIR, ${paths.ckpt_dir}}
filename: ${oc.env:SM_CKPT_FILENAME, "epoch{epoch:03d}-step{step}-valloss{val/loss:.4f}"}

# ------------------------------- Options --------------------------------
auto_insert_metric_name: ${oc.env:SM_CKPT_AUTO_NAME, false}
save_on_train_epoch_end: ${oc.env:SM_CKPT_ON_TRAIN_END, true}
