# configs/training/checkpoint.yaml
# SpectraMind V50 — ModelCheckpoint (swapable)

_target_: pytorch_lightning.callbacks.ModelCheckpoint

monitor: "val/loss"     # change to "val/gll" if you optimize GLL (then set mode: "max")
mode: "min"

save_top_k: 3           # keep best 3
save_last: true
every_n_epochs: 1

dirpath: "${paths.checkpoints}"
filename: "epoch{epoch:03d}-valloss{val/loss:.4f}"
auto_insert_metric_name: false
