# ======================================================================
# SpectraMind V50 — Early Stopping Configuration
# ======================================================================
# Encapsulates PyTorch Lightning EarlyStopping callback parameters.
# Designed to be Hydra-composable and CLI-override-safe. Values can be
# overridden via environment variables (SM_*). Works in concert with
# configs/training/lightning.yaml and fast_ci.yaml profiles.
# ======================================================================

_target_: pytorch_lightning.callbacks.EarlyStopping

# Which metric to monitor — must be logged by Lightning
monitor: ${oc.env:SM_ES_MONITOR, "val/loss"}

# Mode: "min" → stop when metric stops decreasing; "max" → stop when increasing
mode: ${oc.env:SM_ES_MODE, "min"}

# How many validation epochs to wait for improvement
patience: ${oc.env:SM_ES_PATIENCE, 10}

# Minimum relative change to qualify as improvement
min_delta: ${oc.env:SM_ES_MIN_DELTA, 0.0}

# Whether to raise if the monitored metric is missing
strict: ${oc.env:SM_ES_STRICT, true}

# Verbosity of logging
verbose: ${oc.env:SM_ES_VERBOSE, true}
