# ======================================================================
# SpectraMind V50 — Diagnostics & Reporting Config (Hydra 1.x / PL 2.x)
# ======================================================================
# Post-training analyses (metrics + signal/feature diagnostics) with an
# HTML report, JSONL metrics, CSV tables, and a provenance manifest.
# CI/Kaggle-safe (no internet), deterministic, Hydra-composable.
# ======================================================================

# ----------------------------------------------------------------------
# Hydra defaults
# ----------------------------------------------------------------------
defaults:
  - env: local                       # override with env=kaggle or env=ci
  - data: kaggle                     # used only if datamodule paths/splits are needed
  - model: v50                       # enables model-aware diagnostics (SHAP, heads)
  - logger: jsonl                    # consistent with train/predict
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# ----------------------------------------------------------------------
# Experiment metadata
# ----------------------------------------------------------------------
experiment:
  name: "spectramind_v50_diagnose"
  tags: ["v50", "diagnostics", "reports", "fft", "umap", "shap"]
  notes: ""

# ----------------------------------------------------------------------
# Canonical paths (ENV-driven: portable across local/CI/Kaggle)
# ----------------------------------------------------------------------
paths:
  data_root: ${env.data_root}
  artifacts_root: ${env.artifacts_root}
  runs: ${paths.artifacts_root}/runs
  logs: ${hydra:run.dir}/logs
  reports: ${paths.artifacts_root}/reports/diagnostics
  checkpoints: ${paths.artifacts_root}/checkpoints
  schema_dir: ${hydra:runtime.cwd}/schemas
  cache: ${paths.artifacts_root}/.cache/diagnostics

# ----------------------------------------------------------------------
# Inputs
# ----------------------------------------------------------------------
inputs:
  # Model checkpoint to evaluate. Override via CLI or SM_MODEL_CKPT.
  model_ckpt: ${oc.env:SM_MODEL_CKPT, ${paths.checkpoints}/last.ckpt}

  # Evaluation split; either a named split (val|test|custom) consumed by
  # the datamodule, or point eval_file to a CSV/Parquet with ground truth.
  eval_split: ${oc.env:SM_EVAL_SPLIT, "val"}     # one of: val|test|custom
  eval_file:  ${oc.env:SM_EVAL_FILE, null}       # explicit path if custom

  # Optional precomputed predictions CSV; if provided, metrics/analyses run
  # offline on this file (skip inference).
  predictions: ${oc.env:SM_PREDICTIONS, null}

  # Determinism knobs for any stochastic subsampling
  seed: ${env.reproducibility.seed}
  torch_deterministic: ${env.reproducibility.deterministic}

  # Expected spectral bin count (competition schema = 283)
  bin_count: ${oc.env:SM_BIN_COUNT, 283}

# ----------------------------------------------------------------------
# Metrics (leaderboard-aligned + internal sanity)
# ----------------------------------------------------------------------
metrics:
  # Gaussian log-likelihood (primary competition metric)
  gll:
    enabled: true
    weight_fgs1: ${oc.env:SM_GLL_W_FGS1, 58.0}  # keep configurable
    clamp_sigma_min: 1e-6
    clamp_sigma_max: 1e2
    fail_on_nonfinite: true

  mae:
    enabled: true
  rmse:
    enabled: true

  # Distribution checks on σ to detect pathological collapse/overspread
  sigma_stats:
    enabled: true
    ptiles: [5, 25, 50, 75, 95]
    median_min: ${oc.env:SM_SIGMA_MED_MIN, 1e-4}
    median_max: ${oc.env:SM_SIGMA_MED_MAX, 1.0}
    hard_fail: false

# ----------------------------------------------------------------------
# Analyses
# ----------------------------------------------------------------------
analyses:
  # Frequency-domain checks on lightcurves/spectral residuals
  fft:
    enabled: true
    detrend: "poly"       # none|mean|poly
    poly_order: 2
    window: "hann"
    n_fft: 2048
    save_power_spectra: true
    notch: []             # e.g., [50, 60] for mains if applicable

  # Low-dim embedding of latent/features/residuals for cluster/OOD inspection
  umap:
    enabled: true
    n_neighbors: 15
    min_dist: 0.10
    metric: "euclidean"
    sample_size: 5000         # cap for speed
    random_state: ${inputs.seed}
    source: "residuals"       # residuals|mu|latent
    # cache key guards (changes bust the cache)
    cache_key:
      metric: ${analyses.umap.metric}
      n_neighbors: ${analyses.umap.n_neighbors}
      min_dist: ${analyses.umap.min_dist}
      sample_size: ${analyses.umap.sample_size}

  # Model explainability on μ predictions (optionally on σ)
  shap:
    enabled: true
    method: "kernel"          # kernel|sampling|gradient (model-dependent)
    background_size: 256
    sample_size: 512
    max_eval: 5000            # compute budget cap
    explain_sigma: false
    per_sample_timeout_s: 2.5
    # Prefer CPU if CUDA is disabled/unavailable (Kaggle/CI friendliness)
    device: ${oc.env:SM_SHAP_DEVICE, "auto"}   # "auto"|"cpu"|"cuda"

  # Physics/symbolic plausibility checks on spectra
  symbolic_checks:
    enabled: true
    smoothness:
      enabled: true
      max_curvature: 0.02    # |2nd derivative| threshold
    nonneg:
      enabled: true
      tol: -1e-6             # allow tiny numerical noise below zero
    band_coherence:
      enabled: true
      window_bins: 5
      max_zscore: 5.0
    gating:
      hard_fail: false
      max_violation_rate: 0.05

  # Pairwise agreement between μ and σ (heteroscedastic sanity)
  mu_sigma_consistency:
    enabled: true
    corr_min: -0.25           # weakly negative/neutral allowed
    corr_max: 0.75
    hard_fail: false

# ----------------------------------------------------------------------
# Reporting & Artifacts
# ----------------------------------------------------------------------
report:
  out_dir: ${oc.env:SM_DIAG_OUT, ${paths.reports}}
  html:
    enabled: true
    filename: index.html
    title: "SpectraMind V50 — Diagnostics"
    inline_small_images: true
    inline_image_threshold_kb: 256
  save_plots: true
  fig:
    dpi: 160
    style: "default"         # CI/Kaggle-safe
    format: "png"
    tight_layout: true
    grid: true
    backend: "Agg"           # non-interactive (CI/Kaggle safe)
  jsonl_metrics:
    enabled: true
    path: ${report.out_dir}/metrics.jsonl
  tables_csv:
    enabled: true
    dir: ${report.out_dir}/tables
  artifacts:
    save_raw_predictions: true
    raw_predictions_path: ${report.out_dir}/predictions.raw.csv
    save_residuals: true
    residuals_path: ${report.out_dir}/residuals.csv
  integrity_gates:
    enabled: true
    require_bin_count: ${inputs.bin_count}
    require_no_missing_ids: true
    require_finite_values: true
    max_rows: ${oc.env:SM_DIAG_MAX_ROWS, null}   # optional gate

# ----------------------------------------------------------------------
# Provenance & Schema Validation
# ----------------------------------------------------------------------
provenance:
  manifest: ${oc.env:SM_DIAG_MANIFEST, ${paths.artifacts_root}/manifest_diagnostics.json}
  include_git: true
  include_env: true
  include_config_snapshot: true
  include_checksums: true

validate:
  events_schema: ${oc.env:SM_EVENTS_SCHEMA, ${paths.schema_dir}/events.schema.json}
  strict: true
  quiet: false

# ----------------------------------------------------------------------
# Runtime & caching
# ----------------------------------------------------------------------
runtime:
  offline: true                    # enforce no-internet behavior (Kaggle/CI safe)
  num_workers: ${env.num_workers} # reuse env workers
  disable_cuda: ${oc.env:SM_DISABLE_CUDA, false}
  progress: true
  cache:
    enabled: true
    dir: ${paths.cache}
    reuse_shap_background: true
    reuse_umap_embedding: true

# ----------------------------------------------------------------------
# Hydra runtime (under env.artifacts_root)
# ----------------------------------------------------------------------
hydra:
  run:
    dir: ${paths.runs}/${now:%Y-%m-%d_%H-%M-%S}_diagnose
  sweep:
    dir: ${paths.artifacts_root}/sweeps
    subdir: ${hydra.job.num}
  job:
    name: ${experiment.name}
