# configs/env/local.yaml
# ----------------------------------------------------------------------
# Local environment profile — SpectraMind V50
# ----------------------------------------------------------------------
# Purpose:
#   Defines environment-specific settings for running the pipeline
#   on a developer workstation (Linux/macOS, Python 3.11+).
#
# Notes:
#   - Paths are relative unless explicitly absolute.
#   - Kaggle/CI have their own env profiles (see kaggle.yaml).
#   - Keep lightweight, reproducible, and DVC-aware.
# ----------------------------------------------------------------------

# Dataset root (DVC-tracked). Override if data lives elsewhere.
data_dir: ${oc.env:SM_DATA_DIR, data}

# Outputs (Hydra will append run dirs under this root).
outputs_dir: ${oc.env:SM_OUTPUTS_DIR, outputs}

# Cache for intermediate artifacts (calibrated cubes, preprocessed tensors).
cache_dir: ${oc.env:SM_CACHE_DIR, .cache}

# Checkpoints and trained models
checkpoints_dir: ${oc.env:SM_CKPT_DIR, checkpoints}

# Logging (CSV, JSONL, etc.)
logs_dir: ${oc.env:SM_LOGS_DIR, logs}

# Device selection (cpu | cuda | mps). Hydra/Lightning will consume this.
device: ${oc.env:SM_DEVICE, cuda}

# Reproducibility: default RNG seed (can override in training configs)
seed: ${oc.env:SM_SEED, 42}

# Parallelism (set to null for auto)
num_workers: ${oc.env:SM_NUM_WORKERS, 4}

# DVC remote profile (optional; only used if configured)
dvc_remote: ${oc.env:SM_DVC_REMOTE, null}

# ----------------------------------------------------------------------
# This file is composed into train.yaml via:
#   defaults:
#     - env: local
# ----------------------------------------------------------------------
