# docs/mkdocs.yml — SpectraMind V50 Documentation Site
# =============================================================================
# MkDocs builds from docs/ by default. Ensure all referenced files live under docs/.
# If you keep sources elsewhere, add a build step that copies them into docs/.
# =============================================================================

site_name: "SpectraMind V50 — NeurIPS 2025 Ariel Data Challenge"
site_description: "Mission-grade, physics-informed, neuro-symbolic pipeline for exoplanet spectroscopy"
site_author: "SpectraMind V50 Contributors"
site_url: "https://your-org.github.io/spectramind-v50/"
repo_url: "https://github.com/your-org/spectramind-v50"
repo_name: "your-org/spectramind-v50"
edit_uri: "edit/main/docs/"

# Build behaviour
strict: true              # fail the build on bad links/ref errors
use_directory_urls: true  # cleaner URLs

theme:
  name: material
  language: en
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - announce.dismiss
  palette:
    - scheme: default
      primary: indigo
      accent: amber
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  logo: assets/logos/spectramind-logo.png        # docs/assets/logos/...
  favicon: assets/logos/spectramind-logo.png     # docs/assets/logos/...

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/spectramind-v50
      name: GitHub
  generator: false

# ---------- Navigation (ensure all paths exist under docs/) ----------
nav:
  - Home: index.md
  - Quickstart: guides/quickstart.md
  - CLI & Config:
      - Hydra Configs: guides/hydra.md
      - DVC Pipeline: guides/dvc.md
      - Kaggle Usage: guides/kaggle.md
  - Design:
      - Architecture: design/architecture.md
      - Repository Blueprint: design/repository-blueprint.md
      - Scientific Method: context/scientific-method.md
  - Reference:
      - API: reference/api.md
      - Config Schema:
          - Submission: schemas/submission.schema.json
          - Events: schemas/events.schema.json
          - Config Snapshot: schemas/config_snapshot.schema.json
  - Notebooks:
      - Exploration: notebooks/00_exploration.ipynb
      - Alignment & Binning: notebooks/10_alignment_and_binning.ipynb
      - Model Ablation: notebooks/20_model_ablation.ipynb
      - Error Analysis: notebooks/30_error_analysis.ipynb
      - Submission Check: notebooks/99_submission_check.ipynb
  - Challenge Context:
      - Scientific Background: context/scientific-background.md
      - Recent Publications: context/recent-publications.md
  - Meta:
      - Contributing: meta/CONTRIBUTING.md
      - Code of Conduct: meta/CODE_OF_CONDUCT.md
      - Security Policy: meta/SECURITY.md
      - Changelog: meta/CHANGELOG.md
      - License: meta/LICENSE.md

# ---------- Plugins ----------
plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            heading_level: 2
            separate_signature: true
            inherited_members: true
            # filters: []
  - mkdocs-jupyter:
      include_source: true
      execute: false            # set true in CI if you want to execute notebooks on build
      allow_errors: false
      # Notebooks are picked up from nav entries under docs/notebooks/*
      # If you want to kernel-pin:
      # kernel_name: python3
  - mkdocs-awesome-pages-plugin  # honors .pages for custom ordering if present

# ---------- Markdown extensions ----------
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: pymdownx-inline
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# ---------- Assets ----------
# Offline-friendly defaults — place vendor files under docs/assets/...
# If you need MathJax / Mermaid explicitly, bundle locally and reference relatively:
extra_javascript:
  # Example (local MathJax). Place file at docs/assets/vendor/mathjax/tex-mml-chtml.js
  # - assets/vendor/mathjax/tex-mml-chtml.js
  # Example (local Mermaid initialization):
  # - javascripts/init-mermaid.js

extra_css:
  - stylesheets/extra.css

# Optional: live-reload additional paths during local preview (won’t publish)
# watch:
#   - ../src
#   - ../schemas
```

---

## 🔧 What I changed / fixed

* **Removed external CDNs** (MathJax/Mermaid) from `extra_javascript` to keep builds **offline-friendly** by default. If you need them, **vendor locally** under `docs/assets/vendor/...` and uncomment.
* Replaced `awesome-pages` with the **correct plugin name**: `mkdocs-awesome-pages-plugin`.
* **Removed `glob_dir`**, which is not a supported key for `mkdocs-jupyter`. The plugin renders notebooks included in your **`nav`**.
* Verified **Material features** are correct and stable.
* Kept `strict: true` so the build **fails early** if paths are wrong—this is critical for clean docs releases.
* Added **kernel pin** comment for `mkdocs-jupyter` if you need `execute: true` in CI.

---

## 📦 Required pip packages (pin in your docs build env)

```txt
mkdocs>=1.5
mkdocs-material>=9.5
mkdocs-jupyter>=0.24
mkdocstrings>=0.24
mkdocstrings-python>=1.10
mkdocs-git-revision-date-localized-plugin>=1.2
mkdocs-awesome-pages-plugin>=2.9
pymdown-extensions>=10.8
```

> If you’re building docs in a **network-restricted CI** or Kaggle-like environment, **vendor** these wheels into a tools dataset or pre-bake them in a container.

---

## 🧪 Sanity checklist (before building)

* [ ] All `nav` paths exist under `docs/`
* [ ] Notebooks live under `docs/notebooks/` and open locally
* [ ] Any `assets/` paths referenced (logo, CSS, JS) exist
* [ ] If using MathJax/Mermaid explicitly, local files are present and referenced

If you want, I can also generate a minimal **docs skeleton** (empty placeholders for nav paths) so `mkdocs build` passes immediately with `strict: true`.
