name: ci

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'assets/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/kaggle_notebook_ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'assets/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/kaggle_notebook_ci.yml'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write   # SARIF uploads
  actions: read
  packages: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUTF8: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"
  PYTHONHASHSEED: "0"
  MPLBACKEND: "Agg"   # headless-safe matplotlib
  PYTHONWARNINGS: "error::DeprecationWarning,ignore:::pkg_resources"
  ARTIFACT_RETENTION_DAYS: "14"

jobs:
  lint-test-typecheck:
    name: Lint • Typecheck • Unit Tests (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 35
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with: { fetch-depth: 0 }

      - name: 🐍 Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318efd9b4012f1f1a1f4f6c21fc # v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml
            poetry.lock
            setup.cfg
            setup.py

      - name: 🧱 Cache wheels (pip wheelhouse)
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: |
            ~/.cache/pip
            .venv-wheelhouse
          key: ${{ runner.os }}-${{ matrix.python-version }}-wheels-${{ hashFiles('**/requirements*.txt', 'pyproject.toml', 'setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-wheels-

      - name: ♻️ Prime caches (mypy/pytest/ruff)
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: |
            .mypy_cache
            .pytest_cache
            .ruff_cache
          key: ${{ runner.os }}-${{ matrix.python-version }}-lintcache-${{ hashFiles('**/*.py', 'pyproject.toml', 'setup.cfg', 'mypy.ini', '.ruff.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-lintcache-

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Tooling (pin majors; allow patch updates)
          python -m pip install \
            "ruff>=0.5,<1.0" "flake8>=7,<8" "mypy>=1.10,<2" \
            "pytest>=8,<9" "pytest-cov>=4,<5" "pytest-xdist>=3,<4" \
            "pytest-rerunfailures>=14,<15"

      - name: 🔧 Pre-commit (optional)
        if: hashFiles('.pre-commit-config.yaml') != ''
        run: |
          python -m pip install "pre-commit>=3,<4"
          pre-commit run --all-files --show-diff-on-failure

      - name: 🎨 Ruff (format check)
        run: ruff format --check .

      - name: 🔍 Ruff (lint) → SARIF + check
        run: |
          ruff check src/ tests/
          ruff check src/ tests/ --output-format sarif > ruff.sarif || true
          test -s ruff.sarif || echo '{"runs":[]}' > ruff.sarif

      - name: 🐍 Flake8 (lint)
        run: flake8 src/ tests/

      - name: 🧠 Typecheck (mypy)
        run: mypy src/

      - name: 🧪 Unit tests (pytest + coverage)
        env:
          SM_SUBMISSION_BINS: "283"
          PYTEST_ADDOPTS: "-q"
        run: |
          mkdir -p reports
          # retry truly flaky tests once, keep run fast
          pytest -n auto --disable-warnings --maxfail=1 --reruns 1 --reruns-delay 1 \
            --cov=src --cov-branch --cov-report=xml:reports/coverage.xml \
            --durations=25 \
            --junitxml=reports/tests-junit.xml

      - name: 📤 Upload artifacts
        if: always()
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: ci-reports-${{ matrix.python-version }}
          path: |
            ruff.sarif
            reports/
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}

      - name: ⬆️ Upload Ruff SARIF (skip on fork PRs)
        if: always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork != true)
        uses: github/codeql-action/upload-sarif@2e96272c09e5f38e4f0e2e2e7c0cf9c3fb9d0d82 # v3
        with:
          sarif_file: ruff.sarif
          category: ruff-lint

      - name: 🧾 Publish Unit Test Results to Job Summary
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@3f5660f3a9cf74aa02543a9f6f05e07e07d5e7db # v2
        with:
          files: reports/tests-junit.xml

      - name: 📈 Publish Coverage Summary to Job Summary
        if: always()
        uses: irongut/CodeCoverageSummary@66b9cfd6a931ef682a0aabfa4b8a711c823ad950 # v1.3.0
        with:
          filename: reports/coverage.xml
          format: markdown
          output: both

      - name: ☔ Upload coverage to Codecov (optional)
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@4fe8c5f003fae6d2b30dcf8a67b9f1c9c3b87460 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: reports/coverage.xml
          flags: unittests
          fail_ci_if_error: false

  build-and-import:
    name: Build package & import smoke test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [ lint-test-typecheck ]

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with: { fetch-depth: 0 }

      - name: 🐍 Setup Python 3.11
        uses: actions/setup-python@0b93645e9fea7318efd9b4012f1f1a1f4f6c21fc # v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml
            setup.cfg
            setup.py

      - name: 🏗️ Build sdist/wheel (deterministic)
        env:
          SOURCE_DATE_EPOCH: "1704067200"  # 2024-01-01 for reproducible builds
        run: |
          python -m pip install --upgrade pip build twine
          python -m build
          twine check dist/*
          ls -lh dist/

      - name: 🔬 Install built wheel and import
        run: |
          python -m pip install dist/*.whl
          python - <<'PY'
          import importlib, sys
          pkg = 'spectramind'
          importlib.import_module(pkg)
          print(f"Imported {pkg} OK with Python {sys.version.split()[0]}")
          PY

      - name: 📤 Upload build artifacts
        if: always()
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: dist-artifacts
          path: dist/*
          retention-days: 7

  security-pip-audit:
    name: Dependency vulnerability scan (pip-audit → SARIF)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ lint-test-typecheck ]

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: 🐍 Setup Python 3.11
        uses: actions/setup-python@0b93645e9fea7318efd9b4012f1f1a1f4f6c21fc # v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml
            setup.cfg
            setup.py

      - name: 🔧 Install pip-audit
        run: python -m pip install --upgrade pip "pip-audit>=2.7,<3"

      - name: 🔍 Run pip-audit (best-effort) → SARIF
        run: |
          if ls requirements*.txt >/dev/null 2>&1; then
            : > pip-audit.sarif
            for f in requirements*.txt; do
              echo "::group::pip-audit $f"
              pip-audit -r "$f" --format sarif --progress-spinner=off >> pip-audit.sarif || true
              echo "::endgroup::"
            done
          else
            pip-audit --format sarif --progress-spinner=off > pip-audit.sarif || true
          fi
          test -s pip-audit.sarif || echo '{"runs":[]}' > pip-audit.sarif

      - name: ⬆️ Upload SARIF (pip-audit) (skip on fork PRs)
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork != true
        uses: github/codeql-action/upload-sarif@2e96272c09e5f38e4f0e2e2e7c0cf9c3fb9d0d82 # v3
        with:
          sarif_file: pip-audit.sarif
          category: pip-audit

  # Optional: tox lane for monorepos / extra envs (runs only if tox.ini/pyproject has tox config)
  tox:
    name: Tox matrix (optional)
    runs-on: ubuntu-latest
    if: hashFiles('tox.ini', 'pyproject.toml') != ''
    needs: [ lint-test-typecheck ]
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-python@0b93645e9fea7318efd9b4012f1f1a1f4f6c21fc # v5
        with: { python-version: "3.11", cache: pip }
      - run: |
          python -m pip install --upgrade pip tox
          tox -vv || (echo "::warning::tox reported failures"; exit 1)

  # Tiny guard: run only when docs/style files change (fast fail, keeps CI green elsewhere)
  style-docs-guard:
    name: Docs/Style quick guard
    runs-on: ubuntu-latest
    if: >
      contains(github.event.head_commit.message, '[docs]') ||
      hashFiles('**/*.md', '.markdownlint.jsonc', 'typos.toml') != ''
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - run: echo "Docs/style changes detected — main CI unaffected; run docs workflow for full checks."