name: ci

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'assets/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/kaggle_notebook_ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'assets/**'
      - '.github/workflows/docs.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/kaggle_notebook_ci.yml'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write   # SARIF uploads
  actions: read
  packages: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUTF8: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"
  PYTHONHASHSEED: "0"
  MPLBACKEND: "Agg"   # headless-safe matplotlib
  PYTHONWARNINGS: "error::DeprecationWarning,ignore:::pkg_resources"
  ARTIFACT_RETENTION_DAYS: "14"

jobs:
  lint-test-typecheck:
    name: Lint • Typecheck • Unit Tests (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 35
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml
            poetry.lock
            setup.cfg
            setup.py

      - name: Prime caches (mypy/pytest/ruff)
        uses: actions/cache@v4
        with:
          path: |
            .mypy_cache
            .pytest_cache
            .ruff_cache
          key: ${{ runner.os }}-${{ matrix.python-version }}-lintcache-${{ hashFiles('**/*.py', 'pyproject.toml', 'setup.cfg', 'mypy.ini', '.ruff.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-lintcache-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Tooling (pin majors; allow patch updates)
          python -m pip install \
            "ruff>=0.5,<1.0" "flake8>=7,<8" "mypy>=1.10,<2" \
            "pytest>=8,<9" "pytest-cov>=4,<5" "pytest-xdist>=3,<4"

      - name: Pre-commit (optional)
        if: hashFiles('.pre-commit-config.yaml') != ''
        run: |
          python -m pip install "pre-commit>=3,<4"
          pre-commit run --all-files --show-diff-on-failure

      - name: Ruff (format check)
        run: ruff format --check .

      - name: Ruff (lint) → SARIF + check
        run: |
          ruff check src/ tests/
          ruff check src/ tests/ --output-format sarif > ruff.sarif || true
          test -s ruff.sarif || echo '{"runs":[]}' > ruff.sarif

      - name: Flake8 (lint)
        run: flake8 src/ tests/

      - name: Typecheck (mypy)
        run: mypy src/

      - name: Run unit tests (pytest + coverage)
        env:
          SM_SUBMISSION_BINS: "283"
          PYTEST_ADDOPTS: "-q"
        run: |
          mkdir -p reports
          pytest -n auto --disable-warnings --maxfail=1 \
            --cov=src --cov-branch --cov-report=xml:reports/coverage.xml \
            --durations=25 \
            --junitxml=reports/tests-junit.xml

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-reports-${{ matrix.python-version }}
          path: |
            ruff.sarif
            reports/
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}

      - name: Upload Ruff SARIF (skip on fork PRs)
        if: always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork != true)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ruff.sarif
          category: ruff-lint

      - name: Publish Unit Test Results to Job Summary
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: reports/tests-junit.xml

      - name: Publish Coverage Summary to Job Summary
        if: always()
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: reports/coverage.xml
          format: markdown
          output: both

      - name: Upload coverage to Codecov (optional)
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: reports/coverage.xml
          flags: unittests
          fail_ci_if_error: false

  build-and-import:
    name: Build package & import smoke test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [ lint-test-typecheck ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml
            setup.cfg
            setup.py

      - name: Build sdist/wheel (deterministic)
        env:
          SOURCE_DATE_EPOCH: "1704067200"  # 2024-01-01 for reproducible builds
        run: |
          python -m pip install --upgrade pip build twine
          python -m build
          twine check dist/*
          ls -lh dist/

      - name: Install built wheel and import
        run: |
          python -m pip install dist/*.whl
          python - <<'PY'
          import importlib, sys
          pkg = 'spectramind'
          importlib.import_module(pkg)
          print(f"Imported {pkg} OK with Python {sys.version.split()[0]}")
          PY

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/*
          retention-days: 7

  security-pip-audit:
    name: Dependency vulnerability scan (pip-audit → SARIF)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ lint-test-typecheck ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml
            setup.cfg
            setup.py

      - name: Install pip-audit
        run: python -m pip install --upgrade pip pip-audit

      - name: Run pip-audit (best-effort) → SARIF
        run: |
          if ls requirements*.txt >/dev/null 2>&1; then
            : > pip-audit.sarif
            for f in requirements*.txt; do
              echo "::group::pip-audit $f"
              pip-audit -r "$f" --format sarif --progress-spinner=off >> pip-audit.sarif || true
              echo "::endgroup::"
            done
          else
            pip-audit --format sarif --progress-spinner=off > pip-audit.sarif || true
          fi
          test -s pip-audit.sarif || echo '{"runs":[]}' > pip-audit.sarif

      - name: Upload SARIF (pip-audit) (skip on fork PRs)
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork != true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pip-audit.sarif
          category: pip-audit