version: 2

updates:
  # ----------------------------
  # Python — pip (requirements*.txt)
  # ----------------------------
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    target-branch: "develop"
    rebase-strategy: "auto"
    labels: ["dependencies", "security", "pip"]
    # reviewers: ["your-org/sec-reviewers"]
    # assignees: ["andybarta"]
    commit-message:
      prefix: "deps(pip)"
      include: "scope"
    allow:
      - dependency-type: "direct"
    groups:
      core-ml:
        patterns:
          - "torch*"
          - "pytorch*"
          - "lightning*"
          - "hydra*"
          - "omegaconf*"
          - "numpy*"
          - "scipy*"
          - "pandas*"
          - "umap-learn*"
      testing:
        patterns:
          - "pytest*"
          - "hypothesis*"
          - "coverage*"
      linting:
        patterns:
          - "ruff"
          - "flake8*"
          - "mypy*"
          - "black"
          - "isort"
      docs-notebooks:
        patterns:
          - "mkdocs*"
          - "nbconvert*"
          - "nbclient*"
          - "nbformat*"
          - "jupyter*"
      security-sbom:
        patterns:
          - "pip-audit*"
          - "bandit*"
          - "cyclonedx*"
          - "syft*"
          - "trivy*"
    ignore:
      # Reduce churn on heavyweight stacks you don’t vendor directly
      - dependency-name: "opencv-python*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "tensorflow*"
      - dependency-name: "pygobject*"
      # Example: avoid surprise major for core torch; let you opt-in manually
      # - dependency-name: "torch*"
      #   update-types: ["version-update:semver-major"]

  # ----------------------------
  # Python — Poetry (pyproject.toml / poetry.lock)
  # ----------------------------
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "America/Chicago"
    open-pull-requests-limit: 5
    target-branch: "develop"
    rebase-strategy: "auto"
    versioning-strategy: "increase"
    labels: ["dependencies", "security", "poetry"]
    # reviewers: ["your-org/sec-reviewers"]
    commit-message:
      prefix: "deps(poetry)"
      include: "scope"
    allow:
      - dependency-type: "direct"
    groups:
      poetry-core:
        patterns:
          - "*"

  # ----------------------------
  # GitHub Actions (CI/CD)
  # ----------------------------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels: ["dependencies", "security", "ci"]
    # reviewers: ["your-org/ci-admins"]
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    groups:
      ci-core:
        patterns:
          - "actions/*"
          - "github/codeql-action*"
          - "docker/*"
      security-scanners:
        patterns:
          - "aquasecurity/trivy-action*"
          - "anchore/sbom-action*"
          - "anchore/syft-action*"
          - "gitleaks/gitleaks-action*"
      artifacts-cache:
        patterns:
          - "actions/upload-artifact*"
          - "actions/download-artifact*"
          - "actions/cache*"
