name: docs

on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - "assets/diagrams/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "docs/**"
      - "assets/diagrams/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  security-events: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spellcheck:
    name: Spellcheck (typos)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with: { fetch-depth: 0 }
      - name: typos
        uses: crate-ci/typos@v1
        with:
          files: |
            docs
            mkdocs.yml
          config: typos.toml

  markdownlint:
    name: Markdown lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            docs/**/*.md
            README.md
          config: .markdownlint.jsonc

  linkcheck:
    name: External link check (lychee)
    runs-on: ubuntu-latest
    timeout-minutes: 12
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Cache lychee URL cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: .lycheecache
          key: lychee-${{ runner.os }}-${{ hashFiles('docs/**/*.md', 'mkdocs.yml', '.lychee.toml') }}
          restore-keys: |
            lychee-${{ runner.os }}-

      - name: Lychee (cached)
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose
            --no-progress
            --exclude-mail
            --max-concurrency 8
            --cache
            --cache-dir .lycheecache
            --retry-wait-time 3
            --max-retries 4
            --timeout 25
            --accept 200..399,429
            "docs/**/*.md" "mkdocs.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload lychee report
        if: always()
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: lychee-report
          path: |
            ./lychee/results.md
            ./lychee/output.json
          if-no-files-found: ignore
          retention-days: 7

      - name: Summarize linkcheck
        if: always()
        run: |
          echo "### Lychee summary" >> $GITHUB_STEP_SUMMARY
          if [ -f ./lychee/results.md ]; then
            sed -n '1,120p' ./lychee/results.md >> $GITHUB_STEP_SUMMARY || true
          else
            echo "_No lychee report generated._" >> $GITHUB_STEP_SUMMARY
          fi

  build:
    name: Build MkDocs site
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [ spellcheck, markdownlint, linkcheck ]
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_NO_PYTHON_VERSION_WARNING: "1"
    steps:
      - name: Checkout source
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with: { fetch-depth: 0 }

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318efd9b4012f1f1a1f4f6c21fc # v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            docs/requirements.txt
            requirements-docs.txt
            mkdocs.yml

      - name: Cache MkDocs build cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: .cache
          key: mkdocs-${{ runner.os }}-${{ hashFiles('mkdocs.yml', 'docs/**/*.md') }}
          restore-keys: |
            mkdocs-${{ runner.os }}-

      - name: Install Python doc deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f docs/requirements.txt ]; then
            pip install -r docs/requirements.txt
          elif [ -f requirements-docs.txt ]; then
            pip install -r requirements-docs.txt
          else
            pip install \
              "mkdocs==1.6.1" \
              "mkdocs-material==9.5.34" \
              "mkdocs-material-extensions==1.3.1" \
              "mkdocs-mermaid2-plugin==1.2.2" \
              "mkdocs-minify-plugin==0.8.0"
          fi

      - name: Set up Node (for Mermaid CLI pre-render of assets)
        if: ${{ hashFiles('assets/diagrams/**/*.mmd') != '' }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v5
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Mermaid CLI (mmdc)
        if: ${{ hashFiles('assets/diagrams/**/*.mmd') != '' }}
        run: npm i -g @mermaid-js/mermaid-cli@10

      - name: Pre-render Mermaid diagrams in assets (SVG)
        if: ${{ hashFiles('assets/diagrams/**/*.mmd') != '' }}
        run: |
          set -euo pipefail
          OUTDIR="assets/diagrams/_rendered"
          mkdir -p "$OUTDIR"
          while IFS= read -r -d '' f; do
            rel="${f#assets/diagrams/}"
            base="${rel%.*}"
            mkdir -p "$OUTDIR/$(dirname "$rel")"
            mmdc -i "$f" -o "$OUTDIR/${base}.svg" -b transparent
            echo "Rendered: $f -> $OUTDIR/${base}.svg"
          done < <(find assets/diagrams -name '*.mmd' -type f -print0)

      - name: Build MkDocs site (strict)
        env:
          MKDOCS_CONFIG_FILE: mkdocs.yml
        run: |
          set -euo pipefail
          mkdocs build --strict --verbose | tee build.log
          echo "### MkDocs build (tail)" >> $GITHUB_STEP_SUMMARY
          tail -n 200 build.log >> $GITHUB_STEP_SUMMARY || true

      - name: Upload build log and rendered diagrams
        if: always()
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: docs-build-logs-and-diagrams
          path: |
            build.log
            assets/diagrams/_rendered/**/*.svg
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload site artifact (Pages)
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

      - name: Upload site as PR artifact (preview)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: site-preview
          path: site
          retention-days: 7

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
