name: docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'assets/diagrams/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - 'assets/diagrams/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

# Minimal perms for Pages + OIDC
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linkcheck:
    name: External link check (lychee)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lychee (cached URL cache)
        uses: lycheeverse/lychee-action@v2
        with:
          # Check Markdown + MkDocs config; ignore cache-busting querystrings
          args: >
            --verbose
            --no-progress
            --exclude-mail
            --max-concurrency 8
            --cache
            "docs/**/*.md" "mkdocs.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build MkDocs site
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: linkcheck
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements-docs.txt
            mkdocs.yml
            docs/requirements.txt

      - name: Install Python doc deps
        run: |
          python -m pip install --upgrade pip
          # Prefer repo-pinned docs requirements if present; else safe pinned defaults
          if [ -f docs/requirements.txt ]; then
            pip install -r docs/requirements.txt
          elif [ -f requirements-docs.txt ]; then
            pip install -r requirements-docs.txt
          else
            pip install \
              "mkdocs==1.6.1" \
              "mkdocs-material==9.5.34" \
              "mkdocs-mermaid2-plugin==1.2.2" \
              "mkdocs-minify-plugin==0.8.0"
          fi

      - name: Set up Node (for Mermaid CLI pre-render of assets)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Mermaid CLI (mmdc)
        run: npm i -g @mermaid-js/mermaid-cli@10

      - name: Pre-render Mermaid diagrams in assets (SVG)
        if: ${{ hashFiles('assets/diagrams/**/*.mmd') != '' }}
        run: |
          set -euo pipefail
          OUTDIR="assets/diagrams/_rendered"
          mkdir -p "$OUTDIR"
          # Render all .mmd files into SVGs with the same relative layout
          while IFS= read -r -d '' f; do
            rel="${f#assets/diagrams/}"
            base="${rel%.*}"
            mkdir -p "$OUTDIR/$(dirname "$rel")"
            mmdc -i "$f" -o "$OUTDIR/${base}.svg" -b transparent
            echo "Rendered: $f -> $OUTDIR/${base}.svg"
          done < <(find assets/diagrams -name '*.mmd' -type f -print0)

      - name: Build MkDocs site (strict)
        env:
          MKDOCS_CONFIG_FILE: mkdocs.yml
        run: |
          mkdocs build --strict --verbose

      - name: Upload site artifact (Pages)
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Upload built site as PR artifact (preview)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: site-preview
          path: site
          retention-days: 7

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    # Pages deploy only on default branch pushes / manual dispatch, not on forks
    if: ${{ github.event_name != 'pull_request' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4