name: pip-audit

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 7 * * 2"  # Tuesdays

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - run: |
          python -m pip install --upgrade pip pip-audit
          if [ -f requirements.txt ]; then pip-audit -r requirements.txt || true; fi
          if [ -f requirements-dev.txt ]; then pip-audit -r requirements-dev.txt || true; fi
          # Project mode (pyproject/setup.cfg) if present
          if [ -f pyproject.toml ] || [ -f setup.cfg ] || [ -f setup.py ]; then pip-audit || true; fi