name: sbom

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'requirements*.txt'
      - '**/requirements*.txt'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/sbom.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'  # weekly refresh

permissions:
  contents: read
  id-token: write        # for keyless cosign
  packages: read         # needed if OCI_IMAGE points to GHCR

concurrency:
  group: sbom-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'
  ARTIFACT_RETENTION_DAYS: 14
  # Optional: SBOM a container image too (e.g., ghcr.io/owner/repo:latest)
  OCI_IMAGE: ''
  # Optional license allow-list (comma-separated SPDX IDs); empty disables gate
  LICENSE_ALLOWLIST: ''

jobs:
  cyclonedx:
    name: Generate & sign SBOMs (CycloneDX/SPDX)
    runs-on: ubuntu-latest
    timeout-minutes: 18

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      # ---------- Python deps SBOM (CycloneDX) ----------
      - name: 🐍 Set up Python
        uses: actions/setup-python@0b93645e9fea7318efd9b4012f1f1a1f4f6c21fc # v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: |
            **/requirements*.txt
            **/pyproject.toml
            **/poetry.lock
            **/setup.cfg
            **/setup.py

      - name: 🔎 Detect Python dependency manifests
        id: detect
        shell: bash
        run: |
          shopt -s nullglob
          files=( **/requirements*.txt **/pyproject.toml **/poetry.lock **/setup.cfg **/setup.py )
          if (( ${#files[@]} > 0 )); then
            echo "has_python=true" >> "$GITHUB_OUTPUT"
            printf 'Found manifests:\n%s\n' "${files[@]}"
          else
            echo "has_python=false" >> "$GITHUB_OUTPUT"
            echo "No Python manifests found."
          fi

      - name: 📦 Install tools (CycloneDX + helpers)
        run: |
          python -m pip install --upgrade pip
          pip install cyclonedx-bom pipdeptree cyclonedx-cli

      - name: 🧪 Generate Python SBOM (CycloneDX JSON)
        if: ${{ steps.detect.outputs.has_python == 'true' }}
        run: |
          mkdir -p reports
          # Project/resolution mode prefers pyproject/lock/requirements automatically
          cyclonedx-bom -r -o reports/sbom-python.cdx.json || true
          [ -s reports/sbom-python.cdx.json ] && echo "Python SBOM created." || echo "No Python SBOM (no deps detected)."
          pipdeptree --freeze > reports/pipdeptree.txt || true

      # ---------- Repo SBOMs (CycloneDX + SPDX) via Syft ----------
      - name: 📥 Install Syft
        uses: anchore/sbom-action/download-syft@0a56d7a2fa6060d0b4f2b2d1a2dcd71b2f6a3fd1 # v0.20.5 pinned

      - name: 📄 Repo SBOM (CycloneDX JSON)
        run: |
          mkdir -p reports
          syft dir:. -o cyclonedx-json > reports/sbom-repo.cdx.json
          test -s reports/sbom-repo.cdx.json

      - name: 📄 Repo SBOM (SPDX JSON)
        run: |
          syft dir:. -o spdx-json > reports/sbom-repo.spdx.json
          test -s reports/sbom-repo.spdx.json

      - name: 🔄 CycloneDX → SPDX tag:value (readable snapshot)
        run: |
          cyclonedx-cli convert \
            --input-format json \
            --output-format spdx-tag-value \
            --input-file reports/sbom-repo.cdx.json \
            --output-file reports/sbom-repo.spdx.tag

      # ---------- Optional: Container Image SBOM (CycloneDX) ----------
      - name: 🐳 Image SBOM (CycloneDX) if OCI_IMAGE is set
        if: ${{ env.OCI_IMAGE != '' }}
        run: |
          syft "${{ env.OCI_IMAGE }}" -o cyclonedx-json > reports/sbom-image.cdx.json || true
          [ -s reports/sbom-image.cdx.json ] && echo "Image SBOM created." || echo "Image SBOM not generated."

      # ---------- Validate & summarize ----------
      - name: ✅ Validate JSON structure (jq) + CycloneDX validation
        run: |
          set -euo pipefail
          sudo apt-get update -y && sudo apt-get install -y jq
          ok=0
          for f in reports/*.json; do
            [ -f "$f" ] || continue
            jq empty "$f" && echo "✅ JSON valid: $f" && ok=1 || echo "❌ Invalid JSON: $f"
            # Validate CycloneDX docs if applicable
            case "$f" in
              *sbom-*.cdx.json) cyclonedx-cli validate --input-file "$f" || true ;;
            esac
          done
          [ "$ok" = "1" ] || echo "No JSON SBOMs to validate (ok if no deps)."

      - name: 🧾 Summarize components & licenses
        if: always()
        run: |
          echo "### SBOM summary" >> $GITHUB_STEP_SUMMARY
          summarize() {
            f="$1"
            [ -f "$f" ] || return 0
            comps=$(jq -r '[.components[]?.name] | length' "$f" 2>/dev/null || echo 0)
            lic=$(jq -r '
              [.components[]?.licenses[]?
                | (.license.id // .license.name // .expression // "UNKNOWN")] | unique | sort | .[]' "$f" 2>/dev/null || true)
            echo "- $(basename "$f"): components=$comps" >> $GITHUB_STEP_SUMMARY
            [ -n "$lic" ] && printf '  - licenses:\n%s\n' "$(echo "$lic" | sed 's/^/    • /')" >> $GITHUB_STEP_SUMMARY
          }
          summarize reports/sbom-python.cdx.json
          summarize reports/sbom-repo.cdx.json
          summarize reports/sbom-image.cdx.json

      # ---------- Sign SBOM artifacts (keyless via OIDC) ----------
      - name: 🔐 Install Cosign
        uses: sigstore/cosign-installer@1f9f5f017ca3f4f5a82bb2fc77a70b82e40601f1 # v3.7.0 pinned

      - name: ✍️ Sign SBOM JSONs (produce .sig + .cert)
        env: { COSIGN_EXPERIMENTAL: "true" }
        run: |
          set -euo pipefail
          shopt -s nullglob
          for f in reports/*.json; do
            cosign sign-blob --yes "$f" \
              --output-signature "$f.sig" \
              --output-certificate "$f.cert"
          done

      - name: ✅ Verify SBOM signatures (OIDC, repo subject)
        env: { COSIGN_EXPERIMENTAL: "true" }
        run: |
          set -euo pipefail
          shopt -s nullglob
          for f in reports/*.json; do
            [ -f "$f.sig" ] || continue
            cosign verify-blob \
              --certificate "$f.cert" \
              --signature "$f.sig" \
              --certificate-identity-regexp "https://github.com/${{ github.repository }}/*" \
              --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
              "$f"
          done

      # ---------- Optional license allow-list gate ----------
      - name: 📜 Enforce license allow-list (optional)
        if: ${{ env.LICENSE_ALLOWLIST != '' }}
        shell: bash
        run: |
          set -euo pipefail
          IFS=',' read -r -a ALLOWED <<< "${LICENSE_ALLOWLIST}"
          mapfile -t SBOMS < <(ls reports/*.cdx.json 2>/dev/null || true)
          bad=0
          for f in "${SBOMS[@]}"; do
            jq -r '.components[]?.licenses[]? | (.license.id // .license.name // .expression // "UNKNOWN")' "$f" \
            | sort -u | while read -r lic; do
                [[ -z "$lic" ]] && continue
                ok=0; for a in "${ALLOWED[@]}"; do [[ "$lic" == "$a" ]] && ok=1 && break; done
                if [[ $ok -eq 0 ]]; then
                  echo "::error file=$f::Disallowed license detected: $lic"
                  bad=$((bad+1))
                fi
              done
          done
          [[ ${bad:-0} -eq 0 ]] || { echo "License gate failed."; exit 1; }

      - name: 📦 Upload SBOM bundle
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: sbom-bundle
          path: |
            reports/sbom-python.cdx.json
            reports/sbom-repo.cdx.json
            reports/sbom-repo.spdx.json
            reports/sbom-repo.spdx.tag
            reports/sbom-image.cdx.json
            reports/*.sig
            reports/*.cert
            reports/pipdeptree.txt
          if-no-files-found: warn
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
