name: security

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
  schedule:
    - cron: '0 3 * * 1'  # weekly, Mon 03:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    name: Dependency Review (PR gate)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high

  sast-deps:
    name: pip-audit + Bandit + Secrets scan
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml
            poetry.lock

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit bandit detect-secrets

      - name: Prepare security dir
        run: mkdir -p security

      - name: pip-audit → SARIF (non-failing)
        run: |
          if [ -f requirements-dev.txt ]; then pip-audit -r requirements-dev.txt --format sarif -o security/pip-audit.dev.sarif || true; fi
          if [ -f requirements.txt ]; then pip-audit -r requirements.txt --format sarif -o security/pip-audit.main.sarif || true; fi
          if ls requirements-*.txt >/dev/null 2>&1; then
            for f in requirements-*.txt; do
              pip-audit -r "$f" --format sarif -o "security/pip-audit.${f%.txt}.sarif" || true
            done
          fi

      - name: Bandit (non-failing)
        run: |
          if [ -d src ]; then bandit -q -r src -f sarif -o security/bandit.sarif || true; fi

      - name: detect-secrets (non-failing)
        run: detect-secrets scan > security/detect-secrets.json || true

      - name: Upload SARIFs
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: security

      - name: Upload security artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-deps-reports
          path: security
          retention-days: 14

  codeql:
    name: CodeQL (Python)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: python
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3
        with:
          category: '/language:python'

  sbom:
    name: SBOM (Syft / CycloneDX)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Generate SBOM (CycloneDX)
        uses: anchore/syft-action@v0.17.0
        with:
          options: dir:. -o cyclonedx-json=security/sbom.cdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: security/sbom.cdx.json
          retention-days: 30

  container-scan:
    name: Dockerfile Lint + Trivy Scan
    runs-on: ubuntu-latest
    if: hashFiles('Dockerfile') != ''
    steps:
      - uses: actions/checkout@v4

      - name: Prepare security dir
        run: mkdir -p security

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Trivy FS → SARIF (non-failing)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'security/trivy-fs.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          ignore-unfixed: true

      - name: Trivy Config → SARIF (non-failing)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'config'
          format: 'sarif'
          output: 'security/trivy-config.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          exit-code: '0'

      - name: Upload Trivy SARIFs
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: security

      - name: Upload container scan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: security
          retention-days: 14

  gate:
    name: Security Gate
    runs-on: ubuntu-latest
    needs: [dependency-review, sast-deps, codeql, sbom, container-scan]
    steps:
      - name: Summary
        run: |
          echo "Security suite completed:"
          echo " - Dependency Review ✔"
          echo " - pip-audit / Bandit / detect-secrets ✔"
          echo " - CodeQL ✔"
          echo " - SBOM (Syft/CycloneDX) ✔"
          echo " - Trivy (fs + config) ✔"
