name: artifact-sweeper

on:
  schedule:
    - cron: "30 3 * * 0"   # Sundays 03:30 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: artifact-sweeper-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sweep:
    name: 🧹 Delete old artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo (read-only)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove artifacts older than 14 days (keep 5 most recent)
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: 14 days
          skip-tags: true
          skip-recent: 5

      - name: Sweep workflow run logs older than 30 days
        uses: actions/github-script@v7
        with:
          script: |
            const cutoff = new Date();
            cutoff.setDate(cutoff.getDate() - 30);
            const { data: runs } = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
              status: "completed"
            });
            for (const run of runs) {
              if (new Date(run.updated_at) < cutoff) {
                console.log(`Deleting logs for run ${run.id} (${run.name})`);
                await github.rest.actions.deleteWorkflowRunLogs({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id
                });
              }
            }

      - name: Log completion
        run: |
          echo "🧹 Artifact cleanup complete."
          echo "   - Old artifacts (>14d) removed (last 5 kept)."
          echo "   - Workflow run logs >30d pruned."